### ISSUE TITLE
10年間、派手髪を貫く技術

### ISSUE THREAD

**Issue by asumikam** [hachiojipm/ya8-2024-cfp#1]
## 概要
私は高校生の頃から幾度とない髪の毛の脱色を繰り返してきました
10年間にも及ぶ脱色人生の上で「美容師さんから得た知見」「派手髪を維持する上での自分の中に溜まった知見」などがあります
体系的に「派手髪」について話せるだけの何かがあるのでめちゃくちゃ話そうと思います

## 話すであろうこと
- そもそもなぜ脱色をするのか、何がいいのか
- セルフ・フルマネージドの比較・おすすめ
- セルフにおけるうまくいくための勘所
- カラーにおける酸性・塩基性について
- 「脱色してる割にはサラサラだよね」を支える技術

## 参加出来る日時
3/15 10〜18時
(3/16-17で別イベントに参加するので)

## 備考
本当に何でもいいんですよね？

**Comment by uzulla** [comment]
派手髪は完全に一部のエンジニアに需要があるとおもいますし、激論が発生するのではないでしょうか？よろしくお願いいたします！！！

**Comment by asumikam** [comment]
時間があったらスクフェス神奈川のLT練習しようかな
