### ISSUE TITLE
すまん！出ていってくれ！我が家のネズミ対策日記

### ISSUE THREAD

**Issue by hanhan1978** [hachiojipm/ya8-2024-cfp#10]
# 概要

ある日を境に、猫が天井や壁を眺めることが多くなりました。
たまにカサカサという音も聞こえる気がします。これはネズミなのでは....

本トークではネズミをオブザーバブルにし、平和な家庭を維持するために必要な基礎知識と理詰めで考える対応策についてお話します。
実際に行った対策、後日談、及びオブザーブできてしまった動画なども紹介します。

# 話すであろうこと

- 家に出てくるネズミとはなにか？
- ネズミが出てきたらどうしたらいいのか？
- 毒餌、粘着シートは効果があるのか？
- 追い出す薬剤は効果があるのか？
- どうやったら幸せになれるのか？

# 参加出来る日時

3/15 10〜18時
3/16 10〜18時

# 備考

役に立つ！

**Comment by uzulla** [comment]
採択です！！
