### ISSUE TITLE
OrbStackを布教させてください！お願いします！

### ISSUE THREAD

**Issue by tyamahori** [hachiojipm/ya8-2024-cfp#11]
# 内容

自分はMacを利用しています。OrbStackを使う前はDocker Desktop for Macを使っていました。ただ、OrbStackに出会ってから自分は人生が変わりました。この幸せを皆様と共有したいという思いをもとに登壇します。

自分はWebアプリケーション開発者です。1開発者としてOrbStackのどこが素晴らしいのかを説明します。また、各種情報源の共有や自分が主宰しているJapan OrbStack User Group ( https://orbstack.jp/ )について宣伝いたします。

Macユーザーがターゲットとなりますが、ぜひとも聞いてもらえますと嬉しいです。

# 希望登壇日
- 土曜日を希望いたします。

**Comment by uzulla** [comment]
採択しました！
