### ISSUE TITLE
コーヒーを飲みながらわいわい盛り上がる会

### ISSUE THREAD

**Issue by yamato-sorariku** [hachiojipm/ya8-2024-cfp#12]
# 概要

コーヒーを嗜んでいる人も、気になってる人、最近はじめたというひとも語りましょう。
- どんな器具を使ってる？
- どんな淹れ方してる？
- どんな豆を買ってる？
- どんな豆が好み？ 国？品種？精製？
- 淹れるときの温度は？ 水出しってどう？
- このコンビニコーヒーがうまい！
- オススメのコーヒースタンド情報

# 参加出来る日時
2024/03/16 10〜20時頃

**Comment by gennei** [comment]
呼ばれた気がした！座談会参加できます！

**Comment by gennei** [comment]
電気ケトルを持っていけばデモができるのでは？？？

**Comment by yamato-sorariku** [comment]
流しもあるのでとても有りです。（ゴミだけなんとかする）

**Comment by hiroy** [comment]
（ゴミ、出そうなら引き受けますよ（近所なので

**Comment by nasa9084** [comment]
+1

**Comment by wakabadou** [comment]
これはお勧めの機材や豆を持って行って現地で淹れちゃって良いものなのでしょうか？

**Comment by yamato-sorariku** [comment]
ちょっと方向性を変えます！
座談会ではなく、
- コーヒーを入れる人（おすすめしたいものとか、普段飲んでいるもの、普段の機材（できる範囲で）持ち込んで）
- コーヒーを飲んでみたい人
が集まってわいわいお話をする会にしたいと思います！

場所的には PHPerKaigi でアンカンファレンスが行われていたスペースで、そこにテーブルなどを出してやろうと考えてます。

コーヒーを入れる側になりたい人、何人くらいいらっしゃいますかね？

# 機材について
水は ミネラルウォーターをLIFEで購入すればいいかなと思っています。
お湯を沸かすものはこちらで用意します。
提供用に紙コップも購入予定です。

それ以外
- ミル
- ドリッパー
- ペーパー
- サーバ
は入れる人が持参するスタイルです。

**Comment by amarelo-n24** [comment]
コーヒー淹れる側、やりたいです！道具も全部持っていけます。ミルは電動OKですか？

**Comment by yamato-sorariku** [comment]
@amarelo-n24 
ありがとうございます！！
ケトル用に電源タップや延長コードを持っていく予定なので、いけます！

**Comment by yamato-sorariku** [comment]
どの時間帯にやるか？は未確定なのですが、
開催時間は30分程度（長くても1時間以内）と考えています。（そんなに長丁場にはしません）

**Comment by amarelo-n24** [comment]
了解です！ちなみに、やる日は3/16の方で良いですかね？（3/15だと夕方からでないと参加難しそうです…）

**Comment by yamato-sorariku** [comment]
3/16（土）に行います！

**Comment by amarelo-n24** [comment]
了解です！3/16よろしくお願いします！！

**Comment by wakabadou** [comment]
3/16了解です！

幾つかお伺いしたい事項があります。

- 基本水洗いできる場所はない認識でOKでしょうか？
  もし出来るのならばセラフィルター持ち込みたい構え。多分無理だと思うけど。
- コーヒーかすの始末はどうなりますでしょうか？
  重量がえらい事になるのと、破れたら後々まで禍根を残す（というか最悪PHP関係は以降借りれなくなる）ので。
- 湯沸かし、特に電気給湯ですが、電源容量的にはどのようなものが使えますでしょうか？
  一般的な1200W級を延長ケーブルに二つ繋いだら即火災リスクがあるので気になっています。
  そもそも電気ケトルは持ち込み一台のみでみんなで使いまわすイメージでしょうか？（その方が安全なので安心ですが）

**Comment by yamato-sorariku** [comment]
> 基本水洗いできる場所はない認識でOKでしょうか？

確認しますが、ない想定のほうがいいかもです。 液体を捨てる場所はあったはず（こちらも要確認）

> コーヒーかすの始末はどうなりますでしょうか？

各自持ち帰りです。 できる限り水気を絞って持ち帰る感じかなと思っています。

> 湯沸かし、特に電気給湯ですが、電源容量的にはどのようなものが使えますでしょうか？

おっしゃるとおり電源の問題があるので、シェアします。

@wakabadou

**Comment by amarelo-n24** [comment]
当日、自分が焙煎した豆を持っていこうと思っていますが、何杯分くらいを目安に持って行った方がよいですか？なるべく多くの人に行き渡るように準備するつもりですが、念のため確認させてください。

**Comment by wakabadou** [comment]
@yamato-sorariku ご回答ありがとうございます。
ゴミ袋に加えてジップロックも持って行った方が良さそうですね。
湯沸かしについても承知しました。
ちなみに準備予定の湯沸かしはケトル兼用でしょうか？

**Comment by uzulla** [comment]
土曜日、TrackD、午後、ということだけ決定で、お茶会とフェードインフェードアウトとなるので、そのように記述させていただきます。

**Comment by wakabadou** [comment]
すみません。色々伺わせて頂いていたのですが、家庭の都合のよりに参加できなくなりました。申し訳ありません…

**Comment by pudding666** [comment]
こんにちは！
土曜日に「[出張エンジニアティールーム](https://github.com/hachiojipm/ya8-2024/discussions/18)」でお茶会をひらく「ぷぷ」です
同日いうことで、協力して開催する事になりました
どうぞよろしくお願いします！

私はPHPerKaigiのスタッフなので現場の事はだいたいわかります
あと、yamatoさんともある程度お話を進めていたので
それも踏まえて、みなさんの不明・不安点にお答えしていこうと思います

想像しやすいように、先に現場の写真等を共有しますね

①Track D 配置とコンセント図
![IMG_3860 (1)](https://github.com/hachiojipm/ya8-2024-cfp/assets/8502732/056c7fd9-1658-4282-9ed0-a0868579e5f3)
②パントリーと流しの位置
![スクリーンショット 2024-03-12 13 11 00](https://github.com/hachiojipm/ya8-2024-cfp/assets/8502732/9c65a073-1b40-4496-8436-d3bfa2fbe725)
③👀A
![IMG_2669](https://github.com/hachiojipm/ya8-2024-cfp/assets/8502732/b7b469ee-fe6a-4666-aee0-d9fe125e2207)
④👀B
![IMG_2672](https://github.com/hachiojipm/ya8-2024-cfp/assets/8502732/de108ae5-6803-4ef2-a078-1f980bd8c240)

**Comment by pudding666** [comment]
今まで出た質問にお答えします

>基本水洗いできる場所はない認識でOKでしょうか？

PHPerKaigiにいらした方は見たことあると思いますが、無限コーヒーのブースの背の方に調理室があります（画像①ピンクの囲み）
そこに流しがあるので「水洗いOK🙆」です
スポンジや洗剤はティールーム側で用意するので使ってください〜
※そこ以外の小さな手洗い用の流し（黄緑の囲み）は使わないでください

>コーヒーかすの始末はどうなりますでしょうか？

各自お持ち帰りです
```
✅
量によってはご相談に応じます
```

コーヒーかすの量が多い場合は、流し用ネット（ストッキングみたいなやつ。更にキッチンペーパーを被せると良い）を付けたザルを用意する等、流しが詰まらないようにしてくださいね

```
✅
ザルはティールームで用意した物を使っていただいてもOKです🙆
```

**Comment by pudding666** [comment]
>電源容量的な問題

ケトルは2台とも1300Wです
会場の電源は各20Aまでなので系統を分ける必要があります
複数台を同時に使うとなると、それぞれ別の系統の電源からコードを引っ張る必要があります（画像のコンセントの位置を参照）


```
✅
お茶は図の右側のスペースで展開する事になりました
赤と青の電源から引っ張ります
```
![IMG_3864](https://github.com/hachiojipm/ya8-2024-cfp/assets/8502732/6e1402fb-f4b1-48c5-8e56-a4fdc119537a)

**Comment by pudding666** [comment]
**質問**

■ケトルの返却時間
12:30までにケトルをお返しいただきたいのですが大丈夫ですか？
エンジニアティールームは 13:00 からイベントを開始するため、
準備やお湯を沸かす時間を考えて、30分前にはケトルをお返しいただきたいですのですが大丈夫でしょうか

■テーブルについて
エンジニアティールームで使うテーブルも使いますか？
ティールームでは1枠最大7名様を予定しているため、長テーブルを使って簡易カウンター形式にするか
8名がけの円卓があるので、それを利用するか…という感じで考え中です

規模が同じくらいでしたらそのまま使用していただいてOKですし、多少手を加えていただいても。
配線の位置が変わるレベルのレイアウトの違いでしたら、事前に相談させていただきたいです〜🙏

**Comment by pudding666** [comment]
最初の投稿から更新した部分があります
`✅このように表示してます`ので、お手数ですがご確認をお願いします

これまででご不明な点がありましたら仰ってください
新たな質問でも何でもどうぞ！


そして、こちらからお願いがあります🙏
ミネラルウォーターの空きペットボトルを分けてください〜！
2Lとかだと嬉しいです
いくつかあると嬉しいです
よろしくお願いします！！

**Comment by mactkg** [comment]
@yamato-sorariku 
こんにちは。
クレバーコーヒードリッパーを普段使っているので様子をデモしたりわいわいしたいです。（直前ですみません）
もしよければ土曜日準備して持っていくので、デモしてOKだよ〜の返事をください。

持っていく予定のものです:
- ミルと豆
- ドリッパー
- スプーン
- サーバー
- ペーパー
- スケール

**Comment by yamato-sorariku** [comment]
@mactkg 大丈夫です、よろしくお願いします！

**Comment by yamato-sorariku** [comment]
開催時刻、未確定だったんですが
お昼食べた後であろう土曜日の14時-15時にしようと思います

**Comment by yamato-sorariku** [comment]
## コーヒーいれるひと
- @amarelo-n24 
- @gennei 
- @mactkg 
- @yamato-sorariku 

## コーヒー飲む人
- Twitterで告知だけして来てもらう -> @yamato-sorariku 
- 紙コップで提供 ※ 紙コップ回収のために、その場で飲んでもらう
※ ただし先着順

## 備品的な
@yamato-sorariku の電子ケトル（ティファールの1.2Lサイズ）を持っていくのでそれを使います。
紙コップと水（南アルプスの天然水）は下にあるライフで購入

**Comment by yamato-sorariku** [comment]
Post済み
https://x.com/yamato_sorariku/status/1768421218145996966?s=20

**Comment by nasa9084** [comment]
面白モノとして、

* カスカラ
* COE4位のグアテマラ
* 余った豆を入れ続けている闇ブレンド
* 今週発売されたばかりのフィルター
* 紅茶や緑茶を入れるためのドリッパー

などがありますので、この辺を持ち込もうかな〜と思っています

**Comment by gennei** [comment]
V60とフラワードリッパーとエアロプレス持っていこうかなと思っております。

**Comment by yamato-sorariku** [comment]
ORIGAMI ドリッパーとペーパーを円錐とウェーブの二種類を持っていこうと思います！

**Comment by yamato-sorariku** [comment]
1350くらいから準備始めます！
場所はトラックdのここです
![image](https://github.com/hachiojipm/ya8-2024-cfp/assets/7755181/abd937de-25f0-4401-9b9c-4851b09c2ec4)

**Comment by yamato-sorariku** [comment]
皆さんありがとうございました！！！！☕️
