### ISSUE TITLE
みんなで語り尽くせ！私が知りたい、泥臭いインターネット時代の話

### ISSUE THREAD

**Issue by 012xx** [hachiojipm/ya8-2024-cfp#13]
### 概要
こんにちはこんにちは！！
現在22歳の大学4年生です。インターネットはかなり当たり前の環境で育ちました💻
開発においてもいろんな技術があるのは当たり前。最近はもはや情報過多かも。

...ちょっと待って？

もしかしたら私、技術の有り難みがわかっていないかもしれません。
「歴史から学びたい派」の私に、みなさんの知っている「泥臭インターネット時代のアレコレ」を教えてくださ〜〜〜い！！！！！

### 備考
> いくらでも早くおわってOKです。その分雑談しましょう

とのことで、余った時間は聞いてくださっている方とインターネット老人会のようなものをやりたいです（こっちがメイン）。

### 話すこと
- 私が生まれた頃や、開発を始めたころには当たり前だったインターネットの話
- 私が高校時代に商業高校（情報科）で受けた授業のこと
- 私が思う「年上に話すとウケる、昔のインターネット」の話

### みんなと話したいこと・聞きたいこと
- 〇〇がなかった時代はこうやってこうやって....力技でやってたんだよ的な話とか
- みんなが開発を始めたころインターネットの話

### 参加出来る日時
- 2024/03/16 のみ
- 2024/03/15は卒論発表があって参加できないです🙇

**Comment by uzulla** [comment]
枠としてトークでなく、老人会CFXのキックオフになる可能性が若干ありますが採択です！！
