### ISSUE TITLE
型は戦争の道具じゃねえ！ 静的解析バトルで勝負だ！

### ISSUE THREAD

**Issue by zonuexe** [hachiojipm/ya8-2024-cfp#14]
## 概要

202X年、世界は型の炎に包まれた！ だが、型なしは死滅していなかった！

＼ﾃｰﾚｯﾃｰ／

動的言語の型検査や静的型付き言語のリンターなどについて語りましょう。バトル相手が特にいなかったら無限にPHPStanの自慢をします。

## 参加出来る日時

全日程大丈夫です。

**Comment by uzulla** [comment]
採択です！！！！

**Comment by zonuexe** [comment]
@uzulla すみません、このタイミングで非常に申し訳ないのですが採択された時間に(というより明日全日)会場に居るのが厳しそうなので辞退させていただきたく… 🙇
