### ISSUE TITLE
人よりちょっと読書好きだと思う私の、2024年にエンジニアへおすすめしたい本n選

### ISSUE THREAD

**Issue by lacolaco** [hachiojipm/ya8-2024-cfp#17]
あまり本読んでない人よりは読んでると思う私が独断で選んだ、2024年にエンジニアへおすすめしたい本n選を紹介します。
2023年に出版された本を中心に、もっと読まれて話題になってもいいのにと感じている本を布教したいトークです。アフィリエイトリンクはありません。

## 参加出来る日時
いつでもどうにかなると思います

## 備考

~~40分は使わなさそうな予感がします~~ 
資料作ったら普通に時間ギリギリになりそうな感じになったので大丈夫でした

**Comment by uzulla** [comment]
採択です！
余った時間がもしあるなら、みんなにきいてまわりましょう！
