### ISSUE TITLE
fujiwara-ware OSSをひたすら紹介する

### ISSUE THREAD

**Issue by fujiwara** [hachiojipm/ya8-2024-cfp#18]
## 概要

皆さんこんにちは、@fujiwara です。

[プロフィール](https://github.com/fujiwara/fujiwara/blob/main/profile.md) に "最近の趣味はマネージドサービスの隙間を埋める隙間家具のようなツールをGoで作ってOSSにすること" と書いているとおり、OSSをいくつも作っています。それらは主に Go で書かれた、AWS のマネージドサービスを便利に使うためのものなのですが、作ったはいいもののblogすら書いていなかったりして、世間に存在を知られていないものもあるなと気が付きました。

そこで今回は、自作OSSをひたすら紹介しようと思います。もしかしたらその中から、あなたのお仕事に便利に使える道具がなにか見つかるかもしれません。

さらにこれらのOSSをご利用中の皆様がいらっしゃいましたら、この時間で機能要望でもなんでも伝えてもらえたらとも思っています。

### お品書き

1年以内になんらかの更新があったやつから適当に並べておきます。全部紹介できるかは不明です。

- [cfft](https://github.com/fujiwara/cfft)
  - CloudFront FunctionsのテストとCloudFront KVSの操作を便利にするやつ New!
- [ecspresso](https://github.com/kayac/ecspresso)
  - Amazon ECSデプロイツール。多分一番有名?
- [lambroll](https://github.com/fujiwara/lambroll)
  - AWS Lambdaデプロイツール
  - つい最近 v1.0 を出しました。新機能もあるよ
- [ecsta](https://github.com/fujiwara/ecsta)
  - Amazon ECSのタスク操作を便利にできるツール
  - ecspresso からの派生品です
- [tracer](https://github.com/fujiwara/tracer)
  - ECSタスクの一生を全部まとめてみるやつ
- [ridge](https://github.com/fujiwara/ridge)
  - LambdaのFunctionURL/ALB/API GatewayのリクエストをGoの標準httpモジュールで書けるやつ
- [lamblocal](https://github.com/fujiwara/lamblocal)
  - Goで、LambdaでもCLIでも動くような1つのバイナリを作るのに便利なユーティリティ
- [tfstate-lookup](https://github.com/fujiwara/tfstate-lookup)
  - Terraform tfstateを取得してparseして中身を見るCLI/ライブラリ
- [go-amzn-oidc](https://github.com/fujiwara/go-amzn-oidc)
  - Amazon ALB OIDC認証で渡されるJWTを検証するやつ
- [greenlight](https://github.com/fujiwara/greenlight)
  - ヘルスチェックをいい感じにしてくれるやつ
- [ecrm](https://github.com/fujiwara/ecrm)
  - Amazon ECRを安全に掃除してくれるやつ
- [riex](https://github.com/fujiwara/riex)
  - 買っている/もうすぐ期限が切れそうなReserved Instanceを表示してくれるやつ

## 参加出来る日時

- 2024/03/15 10〜20時頃
- 2024/03/16 10〜20時頃

## 備考

金曜日向きだと思います！

**Comment by uzulla** [comment]
勿論採択です！
