### ISSUE TITLE
SREのキャリア、あるいは生態

### ISSUE THREAD

**Issue by cohalz** [hachiojipm/ya8-2024-cfp#19]
## 概要
あなたの周りにはSREと呼ばれている人はいるでしょうか？

いま脳内で思い浮かべた人に対してどういう印象を持ってますか？

自宅でサーバを飼ってそう？ありとあらゆる問題を解決してくれる人？どうやったらなれるのか想像もつかない？

日本でSREの概念が広まってからもう何年も経ちますが、SREを実現するために仕事をしている人たちに対する認識はまだまだ不正確だと感じることがあり、そもそも知る機会もあまりないように思います

そこで自身が未経験から新卒でSREとなり、様々な仕事ができるようになったまでの話を一例として、SREと呼ばれる人に対する解像度を上げる話をします

## 想定聴講
- SRE職にそんなに詳しくない人
  - 注意！Site Reliability Engineering自体の解説はほとんどしません
- SRE職のキャリアについて事例が聞きたい人

## 参加出来る日時
いつでも問題ないです！

## 備考
- 最近人を見る仕事も増えてきたので周りの人がどうやってるかの様子もせっかくなら聞きたいと思ってます(若手の教育とか採用とか...)
  - 廊下でも懇親会でもCFXでもいいです

**Comment by uzulla** [comment]
とりあえず採択ですが、備考欄について、なにかmeetupをしたい場合には、cfxをたてていただいてかまいません！
