### ISSUE TITLE
歌舞は年配の方だけの娯楽ではない！　日本伝統をのぞいてみませんか?  歌舞伎編(初級)

### ISSUE THREAD

**Issue by Rieajiki** [hachiojipm/ya8-2024-cfp#20]
日本伝統の文化を少し深堀してご紹介いたします。
敷居は低く、気軽に楽しめます✨

歌舞伎って、年配の人が見るもんでしょう？って思っている方
歌舞伎って、見て面白いの？って思っている方
歌舞伎って、お高いでしょう？って思っている方
歌舞伎って、ぶっちゃけ、out of 眼中の方

**参加出来る日時**
2024/03/16 10〜20時頃

**Comment by uzulla** [comment]
採択です！
