### ISSUE TITLE
エクササイズにおけるキノコたけのこ論争、筋トレ vs 有酸素 に決着を付ける！

### ISSUE THREAD

**Issue by Songmu** [hachiojipm/ya8-2024-cfp#21]
3/15(金) 17:00- 

# 概要

最近のエンジニア界隈、筋トレばっか盛り上がってずるい！ので、ランニングや自転車等の有酸素運動の魅力を伝えたい。また、筋トレエンジニアの方も招いて、ディベートバトルをしたい。

パッと思いつく範囲で、以下の方々に参加いただけないかと思っておりますが(まだ未相談)、「俺にも語らせろ！」という方はぜひコメントして下さい。

### 筋トレ勢
- @ymotongpoo
- @y-matsuwitter
- @ma3tk

## 有酸素勢
- @naoya
- @fujiwara
- @Songmu (me)

# 参加出来る日時
3/15, 3/16 終日OKです
# 備考
ディスカッション形式でやりたいのですが(最大6名程度)、マイクの用意は可能でしょうか？相談させて下さい。

**Comment by Songmu** [comment]
ディスカッションメンバーが集まらない場合、私がひたすら自転車と有酸素とダイエットと健康について話すトークになります。

**Comment by uzulla** [comment]
採択です

**Comment by Songmu** [comment]
ちょっと参加メンバーの都合を聞いて、登壇希望時間を相談させてもらいたいですが、どの時間帯にしていただいてもなんとかするつもりではいます。 @uzulla

**Comment by Songmu** [comment]
メンバーの都合上、 15日(金) の夕方以降で登壇時間を組んでもらえると嬉しいですが、どこの枠になってもなんとかはします。 @uzulla

**Comment by Songmu** [comment]
CfXにディスカッション立てました。
https://github.com/hachiojipm/ya8-2024/discussions/2#discussioncomment-8581670

**Comment by Songmu** [comment]
Discussionを立てました https://github.com/hachiojipm/ya8-2024/discussions/21
