### ISSUE TITLE
移動を支える技術

### ISSUE THREAD

**Issue by papix** [hachiojipm/ya8-2024-cfp#22]
# 概要

ヤパチーを含め, オフラインで開催されるカンファレンスが復活してきました. 近場で開催されるカンファレンスなら, 電車に乗って移動すればOK... となりますが, 少し離れた場所で開催されるカンファレンスの場合は, "移動"が必要となります.

本セッションでは, そんな｢移動｣に対し, 現時点で発表者が持っている"全て"の知見を開示します. 基本的には国内の移動に関する話題を中心に, 時間に余裕があれば海外の話題も盛り込みます.

## 想定聴講者

- 遠方で開催されるカンファレンスに参加したいが, 移動手段をどのように調べて予約すればいいか, という知見がないという方
- 遠方で開催されるカンファレンスに, 何か変わった移動手段で参加してみたいという方
- 毎回交通機関を適当に予約していて, ちょっとでも節約する術がないか...? と思っている方
- 移動に関する小ネタやTIPSを知りたい方

※ 旅慣れた方からすると, 常識じゃん??? と受け取れる話題が主となります. 予めご了承ください

# 参加出来る日時
- 基本的には2024/03/16を希望します
- もし2024/03/15であれば可能という場合, 朝早め or 夕方遅めの時間にして頂けると幸いです

**Comment by uzulla** [comment]
採択です！
