### ISSUE TITLE
闇 PHP 枠でなにかしゃべる

### ISSUE THREAD

**Issue by sj-i** [hachiojipm/ya8-2024-cfp#24]
- [闇 PHP 枠](https://github.com/hachiojipm/ya8-2024/discussions/16) でなにかしゃべります
- 今のところ「strip された ZTS の処理系バイナリで実行中の PHP プロセスから任意スレッドの Executor Globals のアドレスを気合で得てスクリプトの状態を解析するチャレンジ」みたいなネタを検討しています
- 土曜にトーク可能です

**Comment by uzulla** [comment]
闇PHPというほど人をあつめられなかったので、可能なら通常トークとして変換させてください :bow:
 @sj-i

**Comment by sj-i** [comment]
@uzulla 直前の時期に申し訳ないです、こちら取り下げでお願いできますでしょうか……

もともと子連れでの参加予定でしたが、子供のコロナの発症時期から感染力がギリギリ残っている可能性があることに気づき、参加を控えた方がよさそうです……

**Comment by uzulla** [comment]
了解です！
