### ISSUE TITLE
「サーバーレス」ってなんだろう、踏み込んで調べて説明した後みんなでワイガヤ談義

### ISSUE THREAD

**Issue by seike460** [hachiojipm/ya8-2024-cfp#27]
## 概要

現代では「サーバーレス」というものが当たり前のものになってきています。
しかしこの概念を正しく説明出来る人はなかなかいないのかも知れません。

そこで私が踏み込んでサーバーレスについて深く掘り下げ、その概念、技術的な側面、ビジネスへの影響について話します。
その後、概念の解釈について、技術的なメリデメに関する議論、ビジネスに本当にメリットが有るのかを参加者のみなさまとワイガヤ談義を行います。
つまりは話すためのネタ使って、サーバーレスについてみんなで話すことが目的です。

会場のマイクの状況、部屋の広さなど加味しながら、一方通行では終わらない技術談義を行いましょう。

Amazon Web Services、Google Cloud Platform、Microsoft Azureはもちろん
SupabaseやMoment、TiDB Serverlessなどのサービスを利用した話も大歓迎です。

みんなが好きなサーバーレスを教えてください！

## 参加できる日時:

3/16でお願いします（3/15は参加出来そうにありません）

## 備考

与えられる会場（廊下）の広さに応じてコミュニケーション方法は調整させてください！
（話者にマイクを渡す会話、IRT等）

**Comment by uzulla** [comment]
採択いたします！！
