### ISSUE TITLE
Podcastを3年半続ける技術と得た物

### ISSUE THREAD

**Issue by takaishi** [hachiojipm/ya8-2024-cfp#28]
## 概要

スピーカーは2020年8月からPodcastの配信を毎週欠かさず行っています。継続するためのノウハウと必要なことについて紹介します。
また、Podcastを続けてよかったこと、得たものごとについても紹介します。

このセッションを聞くことで、

- Podcast配信を始めたいけど続くか分からない
- 編集とか難しそうだしどうやればいいかわからない
- Podcast配信して何がうれしいのかわからない

といった疑問を解消できることでしょう。

## 参加出来る日時

(2024/03/15 10〜20時頃 or 2024/03/16 10〜20時頃、これは採択確率に関係します、ご了承ください。

## 備考

40分トークは久々なので採択されたら登壇がんばります。

**Comment by uzulla** [comment]
採択いたします！！
