### ISSUE TITLE
孤独のCTOグルメというやや奇抜な企画をやった目的と効果

### ISSUE THREAD

**Issue by ShoheiMitani** [hachiojipm/ya8-2024-cfp#29]
## 概要

私が所属するスマートバンクでは採用広報の一環で、Kaigi on Rails 2023とYAPC::Hiroshima 2024で **孤独のCTOグルメ** という企画をやりました。

- https://blog.smartbank.co.jp/entry/2023/10/24/120636
- https://blog.smartbank.co.jp/entry/yapc-2024-gourmet

イベントの会場近くの美味しいご飯屋さんをXに投稿するだけの企画なのですが、

- なぜこんな企画をするに至ったのか？？
- これやってどんな効果があったのか？？
- 自腹なの？会社経費なの？？

等々の裏側の話を赤裸々にお話ししたいと思います。

### 私の立ち位置

孤独のCTOグルメは弊社CTOが主役の企画ですが、私はカメラマン兼Xの投稿案作りの一員として参加しておりました。なのでカメラマン視点での当日リポ的な話もできたらいいと思ってます。

## 参加出来る日時

どちらでも大丈夫です！

**Comment by uzulla** [comment]
採択いたします！！
