### ISSUE TITLE
CLIのPHPプログラムを限界まで高速化してみる

### ISSUE THREAD

**Issue by nsfisis** [hachiojipm/ya8-2024-cfp#3]
# 概要

CLI の PHP プログラム（＝ウェブサービスでない）をどこまで高速化できるのか、自作の WebAssembly エンジンを用いて実験した結果をお話しします。

# 話すこと

高速化のために実施したこととそのベンチマーク結果を順に述べていきます。特にオチがあるわけではありません。

# 話さないこと

前述のとおり、CLI のプログラムであり、ウェブサービスではありません。通常の PHP の最適化の文脈で出てくる、データベースやネットワークといった話は**一切出てこない**ことにご留意ください。

# 想定する聞き手

最適化の話が好きな方（PHP ユーザ以外でも）

# 参加出来る日時

* 3/15: ~~**不可**~~ 終日参加可能
* 3/16: 終日参加可能

# 備考

「自作の WebAssembly エンジン」は、[PHPerKaigi 2024 で登壇予定のセッション](https://fortee.jp/phperkaigi-2024/proposal/bc5dc153-17af-4079-8f1b-2660af97e2c8) で用いるものです。

**Comment by uzulla** [comment]
採択です！
そして、16なのも了解です。
(基本的に、トークは15にできるだけもちこむのですが、どうしても土日な人用に16に枠をつくろうとおもいます！)

**Comment by nsfisis** [comment]
@uzulla 3/15 は参加不可、3/16 は参加可能でお伝えしていたのですが、予定を調整し両日参加可能になりました。運営側で都合の良い日に設定していただいて構いません。
