### ISSUE TITLE
「本当の」統計学・確率入門

### ISSUE THREAD

**Issue by kataokatsuki** [hachiojipm/ya8-2024-cfp#30]
## 概要

- ある資料に「〜という結果が分かった」と記載があるが、「それ本当なの？偶然ではなく？」と疑問に思う
- 「〜という傾向が見られる気がする」が、本当なのか分からない
- この集計データで確認するのは「平均値」でいいの？

となったことはありませんか？私は良くあります。

そんな訳で、最近統計学・確率に興味を持ち、趣味で勉強をはじめました。
「へ〜そうなのか！！」と驚くポイントが多く
非常に楽しく、面白いなと感じています。

その中でも基本的な内容を取り上げ、
「これは知っておきたい」
内容を発表したいと思います。

「入門と書いてあるが、入門程度の難易度ちゃうやんけ」というものではなく、
「へえ、面白いな。自分でも勉強してみようかな」
と思えるきっかけとなる、「本当の入門（数学等の背景知識がなくとも楽しめる）」の内容にしたいと考えております。

## 参加出来る日時

特にいつでも大丈夫です。

## 備考(これは必須ではありません)

果たしてどれくらいの時間話せるのか
今の段階で想像がついてないのが多少不安です（15分とかで終わるかもしれない）が、
「いくらでも早く終わってOKとはいえ、〜くらいは話してね」
というラインがあれば教えて頂きたいです！

**Comment by uzulla** [comment]
採択いたします！！

15分で終わるのOKです！

**Comment by kataokatsuki** [comment]
承知しました！
ありがとうございます！
