### ISSUE TITLE
麻雀大会

### ISSUE THREAD

**Issue by shunsock** [hachiojipm/ya8-2024-cfp#31]
Issue Title: 麻雀大会

Issue Description:

- 概要
    - 麻雀でわいわいと交流する会. 本編とは別に裏でやれればいいかなと思っています.
    - 打ちたい人をあらかじめ募集して人数を把握しつつ, [初心者でも麻雀を楽しむ技術](https://github.com/hachiojipm/ya8-2024-cfp/issues/6)もあるのでその場でも募集をかけれたら良いかなと思っています.
- 参加出来る日時
    - 2024/03/15 10〜20時頃 or 2024/03/16 10〜20時頃
    - どちらでも良いですが, 内容の関係上めもりーさんの後だと良いです
- 備考
    - 採択されたら手積みの麻雀卓を持っていきますが, 自動卓を搬入したい人がいるかもなので別途相談したいです.

**Comment by uzulla** [comment]
これはCFP でなく、CFXのようなので、是非あちらでお願いできますか？
https://github.com/hachiojipm/ya8-2024/discussions

**Comment by shunsock** [comment]
承知いたしました！
