### ISSUE TITLE
実録 マルチテナント環境でのGmailガイドライン対応

### ISSUE THREAD

**Issue by ryuichi1208** [hachiojipm/ya8-2024-cfp#32]
## タイトル

実録 マルチテナント環境でのGmailガイドライン対応

## 概要

2023年10月に発表されたGmailのメール送信者ガイドラインのアップデートは、メール配信のエコシステムにおける大きな変革をもたらしました。この新たなガイドラインは、2024年2月に施行され、メール配信者に対してより厳格な要件を課すことになりました。本セッションでは、メールサーバの基本から始まり、新しいGmailガイドラインに対応するための実践的な学び方、アップデート内容の振り返り、そして実際に我々が行った具体的な施策について掘り下げます。

## トピック

* メールサーバ入門(5分)
* Gmaiガイドラインのアップデート内容の振り返り(10分)
  * 内容自体の振り返り
  * 内容をどう受け取ったか
* 我々が行った具体的な施策(インフラ/アプリ)(25分)
  * マルチドメイン環境でのDKIM対応
  * アプリでの対応

## 参加出来る日時

いつでも

## 備考

アプリとインフラで2名での登壇をしたいのですが可能でしょうか？

**Comment by uzulla** [comment]
おそくなりましたが採択です！

> 複数名登壇

全く問題ありません！
