### ISSUE TITLE
Webエンジニアのためのデータエンジニアリング概説

### ISSUE THREAD

**Issue by to-lz1** [hachiojipm/ya8-2024-cfp#33]
## 概要

多様なデータソースから生まれ続けるデータを収集し、加工し、分析やプロダクトに提供する職務、データエンジニアリング。Web企業の中でも徐々に話題に挙がることが増えてきたように思います。

一方、「実際なんで必要なの？」「何が面白いの？」と問われたら...どうでしょう？なんとなくしか知らないな...というWebエンジニアの方も多いのではないでしょうか。

本セッションでは、データエンジニアリングとWebエンジニアリングの双方の経験を持つスピーカーが、「Web開発の視点から見たデータエンジニアリングの特徴」「Webエンジニアリングとの共通点・相違点」、そしてそれらを通して見えてくる「データエンジニアリングの面白さ」についてご紹介します。

例として、以下のようなトピックに焦点を当てます:

* アーキテクチャにおける層（レイヤー）の扱い方
* テストと品質の考え方

## 参加出来る日時

* 2024/03/15 10〜18時頃
* 2024/03/16 10〜20時頃

**Comment by uzulla** [comment]
採択させていただきました！
