### ISSUE TITLE
【供養】DynamoDBでも部分一致検索したかった

### ISSUE THREAD

**Issue by sara-o-mt2** [hachiojipm/ya8-2024-cfp#34]
# 概要
下記のブログの内容をトークの形に整理してお話したいと思います
https://tech.revcomm.co.jp/partial-match-search-with-dynamodb

DynamoDBはスピードやコストの点で期待が高いです。
でもなかなか利用シーンが限られているようで・・・
でもでもよく調べると色々できそうで・・・
でもでもでも試したらやはりちょっとできなかった、という話です。

トーク向けに、ブログでは割愛した、DynamoDBのテーブル設計のためのアクセスパターン整理についてもお話したいと思います。

## 想定聴講者
- DynamoDBは気になるけど実際に使ってサービス開発をしたことはない方
- DynamoDBでKeyの値と一致するデータを取得する基本的な使い方はしたことはあるが、DynamoDBのさらなる可能性について知りたい方

# 参加出来る日時
基本的には2024/03/15 10〜17時頃を希望します
できれば早めの時間だと助かります🙇

**Comment by uzulla** [comment]
採択です！
