### ISSUE TITLE
YAYAPC::Hiroshima 2024の裏側

### ISSUE THREAD

**Issue by ytnobody** [hachiojipm/ya8-2024-cfp#35]
# 概要

YAPC::Hiroshima 2024のアフターイベント [YAYAPC::Hiroshima 2024](https://connpass.com/event/300500/) の開催の裏で何が行われていたのかについて話します。
また、演出というか仕掛けというか、その辺についても話します。

# 参加出来る日時(2024/03/15 10〜20時頃 or 2024/03/16 10〜20時頃、これは採択確率に関係します、ご了承ください。

どの時間帯・どの日でも問題ありません。

# 備考(これは必須ではありません)

とくになし！😹

**Comment by uzulla** [comment]
採択です！
