### ISSUE TITLE
ポリテクセンターによるスキルアップ術

### ISSUE THREAD

**Issue by sat0ken** [hachiojipm/ya8-2024-cfp#36]
## 概要

書籍、勉強会、動画、LLMなど我々ITエンジニアがスキルアップのために活用するリソースはたくさんあります。
しかしあまり知られていないのが、各都道府県に設置された[ポリテクセンター](https://www.jeed.go.jp/location/poly/)ではないでしょうか。

・ポリテクセンターって何？
・求職者向け訓練と在職者向け訓練
・おすすめ講座、気になる講座

ということをお話したいと思います。

## 参加できる日時

金、土どちらもOKです

## 備考

10～15分ぐらいの内容です

**Comment by uzulla** [comment]
採択しました！
