### ISSUE TITLE
何度転職してもデザイナーになってしまうエンジニアの話

### ISSUE THREAD

**Issue by ninjinkun** [hachiojipm/ya8-2024-cfp#37]
## 概要
コードを書いてたつもりがUIデザインまでできちゃって、私また何かやっちゃいました？？

これはUIの実装が好きなエンジニアがなぜかUIデザインまで任されてしまい、そのまま製品がリリースされてしまう話です。怖いことに、同じことが職場を替えながら3回繰り返されます。

このトークは以下のトピックを含みます。

* ninjinkunがUIデザインしてきたプロダクト
  * はてなダイアリースマートフォンビュー
  * 一休レストラン在庫管理Webアプリ
  * Launchable Webアプリ
* エンジニアがUIデザインを行うメリットとデメリット
* UIデザインの勉強方法
* 最近流行ってるデザインエンジニアって何？（今から調べる）

## 参加出来る日時
* 土曜のみです 🙏

**Comment by uzulla** [comment]
採択です！

**Comment by uzulla** [comment]
2024/03/16 15:00 → 16:00 となります:bow:
