### ISSUE TITLE
MySQLとPostgresSQLがキャッキャウフフする 令和最新版（１）_コピー_20240316

### ISSUE THREAD

**Issue by soudai** [hachiojipm/ya8-2024-cfp#5]
# 前回
https://github.com/hachiojipm/yapcasia-8oji-2016mid-timetable/issues/85

## 表記するお名前、SNSアカウント

そーだい
http://twitter.com/soudai1025

yoku0825
http://twitter.com/yoku0825

## 概要

そーだいなるディスカッション。
訳）PostgresSQLとMySQLのエンジニアがその場でテーマを決めてディスカッション。

### テーマ候補
- MySQL 8以降のバージョンアップ
- PostgreSQLの最近の事情
- OSS版のカスタマイズされたディストリビューション
    - Aurora
    - PlanetScale
    - Neon

などなど。
その場で挙手制でテーマを募集するかもしれません。

## 参加出来る日時
soudaiはいつでもOKです。
@yoku0825 さんは行ける日コメントしてください。

## 備考
ただの雑談です。

**Comment by yoku0825** [comment]
3/15(金)が好みです！

**Comment by uzulla** [comment]
金曜了解です！
