### ISSUE TITLE
初心者でも麻雀を楽しむ技術

### ISSUE THREAD

**Issue by m3m0r7** [hachiojipm/ya8-2024-cfp#6]
## 概要

麻雀を難しそうだと思っている方が結構います。実際に麻雀の役は 40 弱あります。
40 弱あるんですが，複数のイレギュラーを除きほとんどがパターンに則っているため，一着を取ることにこだわらないのであれば，実は全ての役を覚えなくても麻雀を楽しむことができます。
最近ではネット麻雀があり，いつアガれる[^1]かわかりやすい仕組みが整っており初心者でも楽しく遊ぶことができます。
そして，何回かプレイを重ねると役を覚えてこれたり戦略を練ることもできます。覚えられるとさらに楽しめます。
麻雀をするにあたって感じてるハードルは実は高くないんだよということをお伝えするのと，そのハードルを超えて麻雀をやる機会を作っていきましょう。

時間が余れば東風[^2]で麻雀のデモをお見せします。

[^1]: ゲームで勝つこと。和了（ホーラ）ともいう。アガリ方は登壇時に解説予定
[^2]: 東風（トンプウ）とは 1 ゲームの単位です。4 人 一 周で親をやりきるのが 1 ゲームです。半荘は 2 ゲームです。オフラインでは半荘が多いですが，ネット麻雀だと東風が多いですね。

**(重要) 麻雀はスポーツです**[^3]

[^3]: (重要) 麻雀はスポーツです[^3]

## 参加出来る日時

どっちでもいいです。金曜日は遅めだと有給使わないで済みます。

## 備考(これは必須ではありません)

登壇内容はテキサスホールデムポーカーでも可

**Comment by uzulla** [comment]
採択です、

そして時刻了解です。
一応質問なのですが、遅めとはどれくらいからになりますか？

**Comment by m3m0r7** [comment]
> 一応質問なのですが、遅めとはどれくらいからになりますか？

何時から何時までやるのかわかってないですが，19:00 以降だと有給使わないで済みそうです！
