### ISSUE TITLE
令和最新版 ソフトウェアエンジニアのためのDJ入門、あるいはDJに学ぶ仕事術

### ISSUE THREAD

**Issue by stefafafan** [hachiojipm/ya8-2024-cfp#7]
## 概要
AWS re:InventのパーティとしてDJイベントが開催されたり、DJを題材としたTVアニメが放映されたりと、DJはソフトウェアエンジニアにとって徐々に身近になってきましたが、そもそもDJがどういうもので、どうすればできるようになるのかを知っていますか？

私は独学でDJを学んで実際に人前でクラブでDJをやった経験が何度もあります。DJは決してただワイワイしているのではなく、念入りな準備と場を俯瞰したプレイが大事な作業です。

このセッションではクラブDJにフォーカスを当ててそもそもどういう手続きでDJというものが行われるのか、準備としてどういうことをやっているのか、人前で当日DJをするとはどういうことなのかを紹介します。また、DJイベントの主催もやったことがあります。主催やDJとしてやっていった中で学んだ知見や、ソフトウェアエンジニアとして仕事に役立つ考え方・Tipsも紹介したいと思っています。

DJをやってみたいと思っている方や、やる予定は別にないけど知見とやらに興味がある方を対象としています。

## 参加できる日時
金、土どちらでも何時でもOKです。

## 備考
実際に会場でDJをしたり音を出したりすることも一瞬検討しましたが、著作権の面のクリアや、そもそも自分が機材を持ち込んだりするのが面倒なので、淡々とトークするのみにとどめるつもりです。

**Comment by uzulla** [comment]
ありがとうございます！採択しました。
DJ的な意味ではないタイテは追って作成しますが金曜日になる想定です。

音については流すことができますが、諸々で迷われた件了解です。
このあたりは気が変われば、いつでも修正してかまいません。よろしくお願いいたします。

**Comment by stefafafan** [comment]
ありがとうございます！承知しました
