### ISSUE TITLE
テック系カンファレンスノベルティ座談会(座談会参加者募集中)

### ISSUE THREAD

**Issue by uzulla** [hachiojipm/ya8-2024-cfp#8]
色々なノベルティをもらったり、作成したりした私が是非座談会をやりたい。

ノベルティ制作に関わる、関わった人で、出てくれる人がいれば是非ご連絡ください。

集まらなかったらボツにします！！！

**Comment by muno92** [comment]
@uzulla  
出ます！

実物を持ち寄って話せると面白そうですね

**Comment by uzulla** [comment]
Tシャツなどもちよりましょう

**Comment by nanbuwks** [comment]
16日なら出れるかも

**Comment by muno92** [comment]
@uzulla  
すみません、こちら16日開催だと大変有り難いです・・・  
（15日は16時以降であればぎりぎり参加出来るかと思います・・・）

**Comment by uzulla** [comment]
はいー、そうしましょう。
