### ISSUE TITLE
コンテナ環境でのminimized perlによるスクリプティングのご提案　〜令和でPerlがこの先生きのこるには〜

### ISSUE THREAD

**Issue by mackee** [hachiojipm/ya8-2024-cfp#9]
## 概要

みなさんDockerなどのコンテナ環境は楽しんでいますか。おー、いい声がしますね。

みなさんperlは楽しんでしますか。あらあら、元気がないですね。

そうなんです、令和6年においてperlコマンドが活躍する機会が少なくなっています。こんなに多機能かつ高速に動くのに。なんでなのか。他にPHPだとかRubyだとか、ユーザーが多くいてユースケースもたくさんある言語がWebにはあるからなんですね。
しかしperlの本来の活躍の場はWebアプリケーションを書くためではなく、あるプログラムとプログラムを結びつけるグルー言語ではないか、というのが今回のトークの提案です。

このトークでは、コンテナ環境においてアプリケーションを記述するための言語とは違う、別のスクリプティング言語の必要な場面が使われつつ、ここにperlが入り込めないかと言うのを提案します。
そして、現状の容量が大きいなどのperlの問題点を挙げつつ、私がコンテナ環境で使うための容量を削減したminimized perlの作成方法について述べます。

そして、シェルスクリプトやMakefileの呪縛からの解放を目指します。

### このトークをして私が達成したいこと

* このトークを聞いた方が「意外とperlも使い道あるじゃん」ってなること
* `#!/bin/bash` と書くときに `#!perl` もあるかも？と脳裏に浮かんでもらえること

## 参加できる日時

15日/16日どちらでも良いですが、私主催のhtmx meetup期間中およびその前後は避けたいです。

## 備考

がんばるぞ！

**Comment by uzulla** [comment]
遅くなりました！採択です！
